lab/analysis/urls.py
from django.conf.urls import patterns, url
# 
urlpatterns = patterns('',
    url(r'^add/(?P<patient_id>\d+)/$', 'analysis.views.add', name='add_analysis'),
    url(r'^group/tests/(?P<group_id>\w+)/$', 'analysis.views.get_testgroup_tests', name='get_group_tests'),
    url(r'^analysis/tests/get_cost/$', 'analysis.views.get_tests_cost', name='get_tests_cost'),
 
    url(r'^delete/(?P<id>\d+)/$', 'analysis.views.delete', name='delete_analysis'),
    url(r'^delete_confirm/(?P<id>\d+)/$', 'analysis.views.confirm_delete', name='confirm_delete_analysis'),
 
    url(r'^edit/(?P<id>\d+)/$', 'analysis.views.edit', name='edit_analysis'),
    url(r'^analysis/$', 'analysis.views.analysis', name='list_analysis'),
    url(r'^analysis/(?P<patient_id>\d+)/$', 'analysis.views.analysis', name='list_analysis'),
    url(r'^analysis/(?P<patient_name>\w+)/$', 'analysis.views.analysis', name='list_analysis'),
    url(r'^analysis/(?P<patient_id>\d+)/(?P<status>\w+)/$', 'analysis.views.analysis', name='list_analysis'),
    url(r'^result/add/(?P<analysis_id>\d+)/$', 'analysis.views.add_result', name='add_result'),
 
#     url(r'^reports/(?P<id>\d+)/$', 'analysis.views.analysis_reports', name='panalysis_reports'),
)

lab/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('attendance.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('django.contrib.auth.urls')),
    url(r'', include('home.urls')),
    url(r'^physician/', include('physician.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^test/', include('medicaltest.urls')),
    url(r'^analysis/', include('analysis.urls')),
    url(r'^', include('inout.urls')),
    url(r'^', include('sendanalysis.urls')),
    url(r'^', include('account.urls')),
    url(r'^lab/', include('medicallab.urls', namespace='lab')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns(settings.MEDIA_URL)

lab/analysis/models.py
# -*- coding: utf-8 -*-
from django.db import models
from medicaltest.models import Test, OtherLabs
from django.core.validators import MaxValueValidator, MinValueValidator
from physician.models import Physician
from patient.models import Patient
from django import forms

class AnalysisTestInfo(models.Model):
    analysis = models.ForeignKey('Analysis', related_name='tests')
    test = models.ForeignKey(Test)
    result = models.FloatField(null=True, blank=True)
    from_lab = models.BooleanField(default=False)
    to_lab = models.BooleanField(default=False)
    lab = models.ForeignKey(OtherLabs, null=True, blank=True)

    def is_from_lab(self):
        return self.from_lab and self.lab
    
    def is_to_lab(self):
        return self.to_lab and self.lab
    
    def cost(self):
        if self.is_from_lab():
            return self.test.receiving_price
        return self.test.price
    
    def sending_cost(self):
        if not self.is_to_lab():
            return 0.0
        return self.test.sending_prices.filter(lab=self.lab)[0].price

    def send_to_lab(self, lab):
        self.lab = lab
        self.to_lab = True
        self.from_lab = False
        self.save()
        return self.sending_cost()
        

    def save(self, *args, **kwargs):
        if not self.result:
            super(AnalysisTestInfo, self).save(*args, **kwargs)
            return
        patient = self.analysis.patient
        sex = patient.sex
        age = patient.get_age_in_days()
        for range in self.test.ranges.all():
            if not range.sex == sex:
                continue
            min_age, max_age = range.get_age_range_in_days()
            if (min_age <= age <= max_age) and (range.range_from <= self.result <= range.range_to):
                super(AnalysisTestInfo, self).save(*args, **kwargs)
                break
        else:
            raise forms.ValidationError("Invalid range")

        def __unicode__(self):
            return self.test.name
    
class Analysis(models.Model):
        physician = models.ForeignKey(Physician, null=True, blank=True)
        patient = models.ForeignKey(Patient, related_name="analysis")
        fast_hours_count = models.IntegerField(default=0, null=False, blank=False, validators=[MinValueValidator(0), MaxValueValidator(24)])
        x_ray_dye = models.BooleanField(default=False)
        delivered = models.BooleanField(default=False)
        date_created = models.DateField(auto_now_add=True)
        
        def cost(self):
            cost = 0.0
            for test in self.tests:
                cost += test.cost()
            return cost

        def __unicode__(self):
            return "%s" % self.patient.name

lab/patient/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError

def _IDValidator(value):
    if not value.isdigit() or len(value) != 14:
        raise ValidationError(u'%s قيمة خاطئة' % value)

def _nameValidator(value):
    value =  value.strip()
    if value in ['normal', 'vip', 'newest', 'oldest', 'alphabet'] or value.isdigit():
        raise ValidationError(u'%s is not a valid name' % value)
    
class Patient(models.Model):
    name = models.CharField(max_length=70,
        null=False, blank=False, unique=True,
        validators=[_nameValidator])
    
    SEX_CHOICES = (('male', 'ذكر'), ('female', 'أنثى'))
    sex = models.CharField(max_length=6, choices=SEX_CHOICES, default="male")
    age_number = models.IntegerField( validators=[MinValueValidator(1), MaxValueValidator(120)])
    AGE_CHOICES = (('day', 'يوم'), ('month', 'شهر'), ('year', 'سنة'))
    age_type = models.CharField(max_length=5, choices=AGE_CHOICES, default="year")
    telephone = models.CharField(max_length=15, blank=True, null=True)
    cell = models.CharField(max_length=14, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    national_ID = models.CharField(max_length=14, validators=[_IDValidator], null=True, blank=True)
    blood_liquidity_treatment = models.BooleanField()
    antibiotique_treatment = models.BooleanField()
    diabetic_treatment = models.BooleanField()
    virus_treatment = models.BooleanField()
    had_blood_transfer = models.BooleanField()
    gland_treatment = models.BooleanField()
    pregnant = models.BooleanField()
    smoker = models.BooleanField()
    liver_treatment = models.BooleanField()
    notes = models.TextField(max_length=200, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def get_age_in_days(self):
        if self.age_type == 'day':
            return self.age_number
        elif self.age_type == 'month':
            return self.age_number * 30
        else:
            return self.age_number * 365
    
    def save(self, *args, **kwargs):
        if self.blood_liquidity_treatment is None:
            self.blood_liquidity_treatment = False
        
        if self.antibiotique_treatment is None:
            self.antibiotique_treatment = False
            
        if self.diabetic_treatment is None:
            self.diabetic_treatment = False
            
        if self.virus_treatment is None:
            self.virus_treatment = False
            
        if self.had_blood_transfer is None:
            self.had_blood_transfer = False
            
        if self.blood_liquidity_treatment is None:
            self.blood_liquidity_treatment = False
            
        if self.gland_treatment is None:
            self.gland_treatment = False
            
        if self.pregnant is None:
            self.pregnant = False
            
        if self.smoker is None:
            self.smoker = False
            
        if self.liver_treatment is None:
            self.liver_treatment = False
            
        super(Patient, self).save(*args, **kwargs)
    
    class Meta:
        ordering = ['-date_added']

    def __unicode__(self):
        return self.name
    
    def fasted(self):
        return self.fast_hours_count > 0

lab/analysis/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Analysis, AnalysisTestInfo
from physician.models import Physician
from medicaltest.models import TestGroup, Test
from django.forms.models import BaseInlineFormSet
from django.contrib.admin.widgets import FilteredSelectMultiple
         
class AddAnalysisTestInfoForm(forms.ModelForm):
    class Meta:
        model = AnalysisTestInfo
     
    def clean(self):
        analysis = self.cleaned_data.get('analysis')
        test= self.cleaned_data.get('test')
        if analysis and test and test not in analysis.tests.all():
            raise forms.ValidationError("هذا التحليل غير موجود بالفحص")
        return self.cleaned_data
 
class CategoriesField(forms.ModelMultipleChoiceField):
    def __init__(self, queryset, **kwargs):
        super(forms.ModelMultipleChoiceField, self).__init__(queryset, **kwargs)
        self.queryset = queryset.select_related()
        self.to_field_name=None

        group = None
        list = []
        self.choices = []

        for category in queryset:
            if not group:
                group = category.group

            if group != category.group:
                self.choices.append((group.name, list))
                group = category.group
                list = [(category.id, category.name)]
            else:
                list.append((category.id, category.name))
        try:
            self.choices.append((group.name, tuple(list)))
        except:
            pass
        self.choices = tuple(self.choices)
class AddAnalysisForm(forms.ModelForm):
    tests = forms.CharField(widget=forms.HiddenInput)
    labs = forms.CharField(widget=forms.HiddenInput)
    
    def clean_tests(self):
        tests = self.cleaned_data.get('tests').split(',')[:-1]
        return tests
    
    def clean_labs(self):
        labs = self.cleaned_data.get('labs').split(',')[:-1]
        return labs

    class Meta:
        model = Analysis
        exclude = ('delivered',)

lab/analysis/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from models import Analysis
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import user_passes_test, login_required
from forms import AddAnalysisForm
from patient.models import Patient
from medicaltest.models import TestGroup, OtherLabs
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound
import json
from medicaltest.models import Test 
from analysis.models import AnalysisTestInfo
from inout.models import Income
import datetime
from django.db import transaction
# 
@login_required
def get_tests_cost(request):
     
    if not request.method == 'POST':
        return HttpResponseNotFound()
     
    tests = request.POST.get("tests").strip().split(",")
    type = request.POST.get("type").strip()
    paid = 0.0
    try:
        paid = int(request.POST.get("paid").strip())
    except:
        pass
     
    if not type in ["standalone", "from_physician", "from_lab"]:
        return HttpResponseNotFound()
         
    tests_ids = []
    for test in tests:
        if test.isdigit():
            tests_ids.append(test)
    res = Test.objects.filter(id__in=tests_ids)
    cost = 0.0
    for test in res:
        if type == "from_lab":
            cost += test.receiving_price
        else:
            cost += test.price
    return HttpResponse(json.dumps({'cost':cost, 'remaining':cost-paid}), mimetype='application/json')
 
@login_required
def get_testgroup_tests(request, TestGroup_id='all'):
    tests = {}
    if TestGroup_id == 'all':
        for test in Test.objects.all():
            tests[test.name] = test.id
    elif not TestGroup_id.isdigit():
        return HttpResponseForbidden()
    else:
        TestGroup = get_object_or_404(TestGroup, pk=TestGroup_id)
     
        for test in TestGroup.tests.all():
            tests[test.name] = test.id
    return HttpResponse(json.dumps(tests), mimetype='application/json')
 
 
@login_required
def add(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    if request.method == 'GET':
        form = AddAnalysisForm()
    else:
        post_data = request.POST.copy()
        post_data['patient'] = patient.id
        form = AddAnalysisForm(post_data)
        if form.is_valid():
            with transaction.commit_on_success():
                tests = Test.objects.filter(id__in=form.cleaned_data['tests'])
                labs = form.cleaned_data['labs']
                analysis = form.save()
                patient.analysis.add(analysis)
                infos =[]
                for i, test in enumerate(tests):
                    info = AnalysisTestInfo()
                    info.analysis = analysis
                    info.test = test
                    if labs[i]  != '0':
                        info.lab = OtherLabs.objects.get(pk=labs[i])
                        info.from_lab = True
                    infos.append(info)
                AnalysisTestInfo.objects.bulk_create(infos)
                Income.objects.create(analysis=analysis)

            return HttpResponseRedirect(reverse('list_analysis'))
    return render(request, 'add_edit_analysis.html', {'form':form,
        'patient_name':patient.name, 'tests':Test.objects.all(), 'labs':OtherLabs.objects.all()})
 
@login_required
def analysis(request, patient_id=0, patient_name='', status=''):
    if request.method == 'POST' and request.POST.get('patient_name'):
        patient_name = request.POST.get('patient_name')
    if patient_id:
        analysis = Analysis.objects.filter(patient__id=patient_id).order_by('-date_created')
        if status and status == 'all':
            analysis = Analysis.objects.filter(patient__id=patient_id).order_by('delivered')
        elif status and status == 'delivered':
            analysis = analysis.filter(delivered=True)
        else:
            return HttpResponseNotFound()
    elif patient_name:
        analysis = Analysis.objects.filter(patient__name__contains=patient_name).order_by('-date_created')
         
    else:
        analysis = Analysis.objects.order_by('-date_created')
    return render(request, 'list_analysis.html', {'analysis':analysis})
 
@user_passes_test(lambda u: u.is_superuser)
def confirm_delete(request, id=0):
    analysis = get_object_or_404(Analysis, pk=id)
    analysis.delete()
    return HttpResponseRedirect(reverse('list_analysis'))
 
@user_passes_test(lambda u: u.is_superuser)
def delete(request, id=0):
    analysis = get_object_or_404(Analysis, pk=id)
    return render(request, 'delete_analysis.html', {'analysis':analysis})
 
@login_required
def edit(request, id=0):
    analysis = get_object_or_404(Analysis, pk=id)
    if request.method == 'GET':
        form = AddAnalysisForm(instance=analysis)
    else:
        old_cost = analysis.paid
        post_data = request.POST.copy()
        post_data['patient'] = analysis.patient.id
        form = AddAnalysisForm(post_data, instance=analysis)
        if form.is_valid():
            new_cost = post_data.get('paid')
            Income.objects.get(date=datetime.date.today()).update(income=new_cost-old_cost)
            form.save()
             
            return HttpResponseRedirect(reverse('list_analysis'))
    return render(request, 'add_edit_analysis.html', {'form':form, 'patient_name':analysis.patient.name})
 
def add_result(request, analysis_id):
    analysis = get_object_or_404(Analysis, pk=analysis_id)
    tests = analysis.tests.all()
    errors = {}
    if request.method == "GET":
        return render(request, 'add_result.html', {'tests':tests, 'patient': analysis.patient, 'erros':errors})
    else:
         
        for test in tests:
            value = request.POST.get(test.name, '0')
            test.value = value if value else '0'
            try:
                int(value)
                value = float(value)
            except ValueError:
                errors[test.name] = "من فضلك ادخل ارقام"
                break
            try:
                AnalysisTestInfo.objects.create(test=test, analysis=analysis, result=value)
            except:
                errors[test.name] = "من فضلك ادخل قيمة صحيحة لهذا التحليل"
                break
                       
        else:
            return HttpResponseRedirect(reverse('home'))
        return render(request, 'add_result.html', {'tests':tests, 'patient': analysis.patient, 'errors':errors})
 
@login_required
@user_passes_test(lambda u: u.is_superuser)
def Analysis_reports(request, id=0):
    Analysis = get_object_or_404(Analysis, pk=id)
    return render(request, 'Analysis_reports.html', {})

lab/analysis/templates/add_edit_analysis.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
<script src="{% static 'js/jquery.multi-select.js' %}"></script>
<script src="{% static 'js/quicksearch.js'%}"></script>
<script>
	$(document).ready(function(){
		$("#submit").click(function(){
			var test_lab = {};
			var tests = '';
			var labs = '';
			$('input:checked').each(function(){
				labs += $(this).parent().find('select').val();
				labs += ',';
				tests += $(this).val();
				tests += ',';
			});
			
			$("#id_tests").val(tests);
			$("#id_labs").val(labs);
			$("#form").submit();
		});
	});
	
		
	
</script>
{% endblock %}

{% block css %}
<link href="{% static 'css/multi-select.css' %}" rel="stylesheet" type="text/css" />

{% endblock %}
{% block body %}
<div class="panel" id="home">
	<fieldset align="center">
		<legend align="right">
			<h1>إضافة فحص</h1>
		</legend>
		<form method="post" id="form">
			{% csrf_token %}
			<table align="right">
				{{form.errors}}
				<tr>
					<td align="right">{{patient_name}}</td>
					<td align="right"><label for="id_name">:اسم المريض</label></td>
				</tr>
				<tr id=>
					<td align="right">{{form.physician}}</td>
					<td align="right"><label>:اسم الطبيب</label></td>
				</tr>
				
				<tr>
					<td align="right">{{form.fast_hours_count}}</td>
					<td align="right"><label for="id_name">:عدد ساعات الصيام</label></td>
				</tr>
				<tr>
					<td align="right">{{form.x_ray_dye}}</td>
					<td align="right"><label for="id_name">:أشعة بالصبغة</label></td>
				</tr>
				
				<tr>
						{{form.tests}}
						{{form.labs}}
				</tr>
			</table>
		</form>
	</fieldset>
	
	<fieldset>
		<legend>
			التحاليل
		</legend>
		
		<button id="submit">ADD</button>
		{% for test in tests %}
		<div class="test">
			<input type="checkbox" value="{{test.id}}" class="test-checkbox">{{test.name}} 
			
			<select class="labs">
				<option value="0">------</option>
				{% for lab in labs %}
				<option value="{{lab.id}}">{{lab.name}}</option>
				{% endfor %}
			</select>
			محول من :
			<br/>
		</div>
		{% endfor %}
	</fieldset>
</div>
{% endblock %}

lab/analysis/templates/add_result.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block body %}
<div class="panel" id="home">
	<fieldset align="center">
		<legend align="right">
			<h1>إضافة نتيجة</h1>
		</legend>
		<form method="post" id="form">
			{% csrf_token %}
			<table align="right">
				{% for field, error in errors.items %}
					<li>
						{{field}} : {{error}}
					</li>
				{% endfor%}
				<tr>
					<td align="right">{{patient.name}}</td>
					<td align="right"><label for="id_name">:اسم المريض</label></td>
				</tr>
				
				{% for test in tests%}
				<tr>
				<td><input name="{{test.name}}" value="{{test.value}}"></td>
				<td align="right"><label for="id_name">{{test.name}}</label></td>
				</tr>
				{% endfor %}
				
				<tr>
					<br/>
					<td align="right">
					<input type="submit" id="submit" value="إضافة">
					</td>
				</tr>
			</table>
		</form>
	</fieldset>
</div>
{% endblock %}

lab/analysis/templates/delete_analysis.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
<script>
	$(document).ready(function() {

		$("#analysis").addClass('selected');

	}); 
</script>
{% endblock %}

{% block body %}

<div class="panel" id="home">
	<fieldset align="center">
		<legend align="right">
			<h1> تأكيد حذف فحص </h1>

		</legend>
		<br/>
		<table border="0" align="center" width="500">

			<tr>
				<td>{{analysis.patient.name}} </td>
				<td> اسم المريض</td>
			</tr>
			
			<tr>
				<td>{{analysis.date_created}} </td>
				<td> التاريخ</td>
			</tr>


			<tr>
				{% for test in analysis.tests.all %}
				<td>{{test.name}} </td>
				{% endfor %}
				<td> التحاليل</td>
			</tr>


			
					<tr>
						<td>
						<form action="{% url 'confirm_delete_analysis' analysis.id %}" method="post">
							{% csrf_token %}
							<input  type="submit" value="تأكيد الحــــــــذف"/>

						</form></td>
					</tr>
				</table>

			</fieldset>

</div>
{% endblock %}

lab/analysis/templates/list_analysis.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block body %}

	<div class="panel" id="home">
	<fieldset align="center">
	<legend align="right">
		<h1>
			  بــحث عن فحص باستخدام اسم المريض 
			  
		</h1>
	</legend>
	<form method="post" action="{% url 'list_analysis'%}" align="right">
		{% csrf_token %}
		<input type="submit" value="بــحث">
		<input name="patient_name" type="text" />
	</form>
	</fieldset>
	
	<fieldset align="center">
	<legend align="right">
		<h1>
			
			الفحوصات 
		</h1>
		
	 </legend>
	<br/>
	
	{% if not analysis %}
		<div align="center">عفوا .... لا توجد نتائج</div>
	{% else %}
	<table border="1" align="center" width="500">
		<tr>
			<th>أخرى</th>
		<th>تم تسليمه</th>
		<th>اسم المريض</th><br />
		<th>الرقم التعريفى</th>
		
		</tr>
		{% for record in analysis %}
		<tr>
			<td>
				<a href="{% url 'delete_analysis' record.id %}" > 
				<img src="{% static 'images/delete.png' %}" title="حذف الفحص" />
				</a>
				
				<a href="{% url 'edit_analysis' record.id %}" > 
				<img src="{% static 'images/edit.png' %}" title="تعديل">
				</a>
				
				
			</td>
			
			<td>
				{% if record.delivered %}
					<input type="checkbox" disabled checked >
				{% else %}
				<input type="checkbox" disabled>
				{%endif%}
				</td>

			<td><a href="{% url 'edit_analysis' id=record.id %}">{{record.patient.name}}</a></td>
			<td><a href="{% url 'edit_analysis' id=record.id %}">{{record.id}}</a></td>
		</tr>
			{% endfor %}
	</table>
{%endif%}
</fieldset>				

</div>
{% endblock %}