lab/physician/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^add', 'physician.views.add', name='add_physician'),
    url(r'^delete/(?P<id>\d+)/$', 'physician.views.delete', name='delete_physician'),
    url(r'^delete_confirm/(?P<id>\d+)/$', 'physician.views.confirm_delete', name='confirm_delete_physician'),
    url(r'^edit/(?P<id>\d+)/$', 'physician.views.edit', name='edit_physician'),
    url(r'^physicians/$', 'physician.views.physician', name='list_physician'),
    url(r'^physicians/(?P<param>\w+)/$', 'physician.views.physician', name='list_physician'),
    url(r'^reports/(?P<id>\d+)/$', 'physician.views.physician_reports', name='physician_reports'),
)

lab/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('attendance.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('django.contrib.auth.urls')),
    url(r'', include('home.urls')),
    url(r'^physician/', include('physician.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^test/', include('medicaltest.urls')),
    url(r'^analysis/', include('analysis.urls')),
    url(r'^', include('inout.urls')),
    url(r'^', include('sendanalysis.urls')),
    url(r'^', include('account.urls')),
    url(r'^lab/', include('medicallab.urls', namespace='lab')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns(settings.MEDIA_URL)

lab/physician/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.exceptions import ValidationError

def _nameValidator(value):
    value =  value.strip()
    if value in ['normal', 'vip', 'newest', 'oldest', 'alphabet'] or value.isdigit():
        raise ValidationError(u'%s is not a valid name' % value)
    
class Physician(models.Model):
    name = models.CharField(max_length=40,
        null=False, blank=False, unique=True,
        validators=[_nameValidator],
        error_messages={'unique':"موجود مسبقا"})
    address = models.CharField(max_length=70, null=True, blank=True)
    telephone = models.CharField(max_length=15, blank=True, null=True)
    cell = models.CharField(max_length=15, blank=True, null=True)
    is_vip = models.BooleanField(default=True)
    
    class Meta:
        ordering=['-is_vip', 'name']
    def __unicode__(self):
        return self.name

lab/physician/forms.py
from django import forms
from models import Physician

class AddPhysicianForm(forms.ModelForm):
    class Meta:
        model = Physician

lab/physician/views.py
from django.shortcuts import render, get_object_or_404
from forms import AddPhysicianForm
from models import Physician
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import user_passes_test

@user_passes_test(lambda u: u.is_superuser)
def add(request):
    if request.method == 'GET':
        form = AddPhysicianForm()
    else:
        form = AddPhysicianForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list_physician'))
    return render(request, 'add_physician.html', {'form':form})

@user_passes_test(lambda u: u.is_superuser)
def physician(request, param=''):
    if request.method == "POST":
        param = request.POST.get("param")
    
    if not param:
        physicians = Physician.objects.all()
    elif param == "vip":
        physicians = Physician.objects.filter(is_vip=True).order_by('name')
    elif param == "normal":
        physicians = Physician.objects.filter(is_vip=False).order_by('name')
    else:
        physicians = Physician.objects.filter(name__contains=param.strip()).order_by('name')
    return render(request, 'physicians.html', {'physicians':physicians})

@user_passes_test(lambda u: u.is_superuser)
def confirm_delete(request, id=0):
    physician = get_object_or_404(Physician, pk=id)
    physician.delete()
    return HttpResponseRedirect(reverse('list_physician'))

@user_passes_test(lambda u: u.is_superuser)
def delete(request, id=0):
    physician = get_object_or_404(Physician, pk=id)
    return render(request, 'delete_physician.html', {'physician':physician})

@user_passes_test(lambda u: u.is_superuser)
def edit(request, id=0):
    physician = get_object_or_404(Physician, pk=id)
    if request.method == 'GET':
        form = AddPhysicianForm(instance=physician)
    else:
        form = AddPhysicianForm(request.POST, instance=physician)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list_physician'))
    return render(request, 'edit_physician.html', {'form':form})

@user_passes_test(lambda u: u.is_superuser)
def physician_reports(request, id=0):
    physician = get_object_or_404(Physician, pk=id)
    return render(request, 'physician_reports.html', {})

lab/physician/templates/add_physician.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
	<script>
		$(document).ready(function(){
			
			$("#physician").addClass('selected');
    		
		});
	</script>
{% endblock %}

{% block body %}
<div class="panel" id="home">
<fieldset align="center">
<legend align="right"> <h1>إضافة طبيب</h1></legend>
<form action="{% url 'add_physician' %}" method="post">
	{% csrf_token %}
	<table align="right">
		<tr>
			
			<td align="left">{{form.name}}</td>
			<td align="right"><label for="id_name">:الإسم</label></td>
			
	
		</tr>
		<tr><td align="left" style="color:red;">{{form.name.errors}} </td></tr>
		<tr>
			<td align="left">{{form.address}}</td>
			<td align="right"> <label for="id_address">:العنوان</label></td>
			{{form.address.errors}}
			
			
	
		</tr>
	
	<tr>
		<td align="left">	{{form.telephone}}</td>
			<td align="right"> <label for="id_telephone">:رقم التليفون</label></td>
		{{form.telephone.errors}}
		
	</tr>
	
	<tr>
	
			<td align="left">	{{form.cell}}</td>
			<td align="right"> <label for="id_cell">:الهاتف المحمول</label></td>
			
			{{form.cell.errors}}
	
	
	</tr>
	
	<tr>
		<td align="left">	{{form.is_vip}}</td>
			<td align="right"> <label for="id_is_vip">:متعاقد معه</label></td>

	{{form.is_vip.errors}}
	
	
	</tr>
	
	<tr>
		<td align="right">
		<input type="submit" value="إضافة">
		</td> 
	</tr>
	</table>
</form>
</fieldset>
</div>
{% endblock %}

lab/physician/templates/delete_physician.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
<script>
	$(document).ready(function() {

		$("#physician").addClass('selected');

	}); 
</script>
{% endblock %}

{% block body %}

<div class="panel" id="home">
	<fieldset align="center">
		<legend align="right">
			<h1> تأكيد حذف طبيب </h1>

		</legend>
		<br/>
		<table border="0" align="center" width="500">

			<tr>

				<td> اسم الطبيب :   {{physician.name}} </td>
			</tr>

			<tr>
				<td> العنوان :   {{physician.address}} </td>
			</tr>

			<tr>
				<td> التليفون :   {{physician.telephone}} </td>
			</tr>

			<td> الهاتف المحمول :   {{physician.cell}} </td>
			<tr>
				<td>{% if physician.is_vip %}
				<input type="checkbox" disabled="disabled">
				{% else %}
				<input type="checkbox" checked="checked" disabled="disabled">
				{% endif %}
				: تم التعاقد معه </td>
			</tr>

			<tr>
				<td>
				<form action="{% url 'confirm_delete_physician' physician.id %}" method="post">
					 {% csrf_token %}
					<input  type="submit" value="تأكيد الحــــــــذف"/>

				</form></td>
			</tr>
		</table>

	</fieldset>

</div>
{% endblock %}

lab/physician/templates/edit_physician.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
	<script>
		$(document).ready(function(){
			
			$("#physician").addClass('selected');
    		
		});
	</script>
{% endblock %}

{% block body %}
<div class="panel" id="home">
<fieldset align="center">
<legend align="right"> <h1>تعديل بيانات طبيب</h1></legend>
<form method="post">
	{% csrf_token %}
	<table align="right">
		<tr>
			
			<td align="left">{{form.name}}</td>
			<td align="right"><label for="id_name">:الإسم</label></td>
		</tr>
		<tr><td align="left" style="color:red;">{{form.name.errors}} </td></tr>
		<tr>
			<td align="left">{{form.address}}</td>
			<td align="right"> <label for="id_address">:العنوان</label></td>
			{{form.address.errors}}
			
			
	
		</tr>
	
	<tr>
		<td align="left">	{{form.telephone}}</td>
			<td align="right"> <label for="id_telephone">:رقم التليفون</label></td>
		{{form.telephone.errors}}
		
	</tr>
	
	<tr>
	
			<td align="left">	{{form.cell}}</td>
			<td align="right"> <label for="id_cell">:الهاتف المحمول</label></td>
			
			{{form.cell.errors}}
	
	
	</tr>
	
	<tr>
		<td align="left">	{{form.is_vip}}</td>
			<td align="right"> <label for="id_is_vip">:متعاقد معه</label></td>

	{{form.is_vip.errors}}
	
	
	</tr>
	
	<tr>
		<td align="right">
		<input type="submit" value="تعديل">
		</td> 
	</tr>
	</table>
</form>
</fieldset>
</div>
{% endblock %}

lab/physician/templates/physician_reports.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
	<script>
		$(document).ready(function(){
			
			$("#physician").addClass('selected');
    		
		});
	</script>
{% endblock %}

{% block body %}

{% endblock %}

lab/physician/templates/physicians.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
	<script>
		$(document).ready(function(){
			
			$("#physician").addClass('selected');
    		
		});
	</script>
{% endblock %}

{% block body %}

<div class="panel" id="home">
	
	<fieldset align="center">
	<legend align="right">
		<h1>
			بــحث عن طبيب
		</h1>
	</legend>
	<form method="post" action="{% url 'list_physician'%}" align="right">
		{% csrf_token %}
		<input type="submit" value="بــحث">
		<input type="text" name="param" id="soso"/>
	</form>
	</fieldset>

	<fieldset align="center">
	<legend align="right">
		<h1>
			<a href="{% url 'list_physician' 'normal' %}"><img src="{% static 'images/non_vip_doctor.png'%}" title="أطباء غير متعاقد معهم"></a>
			<a href="{% url 'list_physician' 'vip' %}"><img src="{% static 'images/vip_doctor.png'%}" title="أطباء متعاقد معهم"></a>
			<a href="{% url 'list_physician' %}"><img src="{% static 'images/all_doctors.png'%}" title="كل الأطباء"></a>
			<a href="{% url 'add_physician'%}"><img src="{% static 'images/add.png'%}" title="إضافة طبيب جديد"></a>
				
			الأطباء
		</h1>
		
	 </legend>
	<br/>
	
	{% if not physicians %}
		<div align="center">عفوا .... لا توجد نتائج</div>
	{% else %}
	<table border="1" align="center" width="500">
		<tr>
		<th>أخرى</th>
		<th>متعاقد معه</th>
		<th>رقم الهاتف المحمول</th>
		<th>رقم التليفون</th>
		<th>العنوان</th>
		<th>اسم الطبيب</th>
		
		</tr>
		{% for record in physicians %}
		<tr>
			<td>
				<a href="{% url 'delete_physician' record.id %}" > 
				<img src="{% static 'images/delete.png' %}" title="حذف الطبيب" />
				</a>
				
				<a href="{% url 'physician_reports' record.id %}" > 
				<img src="{% static 'images/report.png' %}" title="عرض تقـــارير الطبيب" />
				</a>
			</td>
			<td>
			{% if record.is_vip %}
				<input type="checkbox" disabled="disabled" checked="checked"/>
			{% else %}
				<input type="checkbox" disabled="disabled" />
			{% endif %}
			</td>
			<td>{{record.cell}}</td>
			<td>{{record.telephone}}</td>
			<td>{{record.address}}</td>
			<td><a href="{% url 'edit_physician' id=record.id %}">{{record.name}}</a></td>
		</tr>
			{% endfor %}
	</table>
{%endif%}
</fieldset>				

</div>
{% endblock %}