lab/patient/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^add', 'patient.views.add', name='add_patient'),
    url(r'^delete/(?P<id>\d+)/$', 'patient.views.delete', name='delete_patient'),
    url(r'^delete_confirm/(?P<id>\d+)/$', 'patient.views.confirm_delete', name='confirm_delete_patient'),
    url(r'^edit/(?P<id>\d+)/$', 'patient.views.edit', name='edit_patient'),
    url(r'^patients/$', 'patient.views.patients', name='list_patients'),
    url(r'^patients/(?P<param>\w+)/$', 'patient.views.patients', name='list_patients'),
    url(r'^reports/(?P<id>\d+)/$', 'patient.views.patient_reports', name='patient_reports'),
)

lab/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('attendance.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('django.contrib.auth.urls')),
    url(r'', include('home.urls')),
    url(r'^physician/', include('physician.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^test/', include('medicaltest.urls')),
    url(r'^analysis/', include('analysis.urls')),
    url(r'^', include('inout.urls')),
    url(r'^', include('sendanalysis.urls')),
    url(r'^', include('account.urls')),
    url(r'^lab/', include('medicallab.urls', namespace='lab')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += staticfiles_urlpatterns(settings.MEDIA_URL)

lab/patient/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError

def _IDValidator(value):
    if not value.isdigit() or len(value) != 14:
        raise ValidationError(u'%s قيمة خاطئة' % value)

def _nameValidator(value):
    value =  value.strip()
    if value in ['normal', 'vip', 'newest', 'oldest', 'alphabet'] or value.isdigit():
        raise ValidationError(u'%s is not a valid name' % value)
    
class Patient(models.Model):
    name = models.CharField(max_length=70,
        null=False, blank=False, unique=True,
        validators=[_nameValidator])
    
    SEX_CHOICES = (('male', 'ذكر'), ('female', 'أنثى'))
    sex = models.CharField(max_length=6, choices=SEX_CHOICES, default="male")
    age_number = models.IntegerField( validators=[MinValueValidator(1), MaxValueValidator(120)])
    AGE_CHOICES = (('day', 'يوم'), ('month', 'شهر'), ('year', 'سنة'))
    age_type = models.CharField(max_length=5, choices=AGE_CHOICES, default="year")
    telephone = models.CharField(max_length=15, blank=True, null=True)
    cell = models.CharField(max_length=14, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    national_ID = models.CharField(max_length=14, validators=[_IDValidator], null=True, blank=True)
    blood_liquidity_treatment = models.BooleanField()
    antibiotique_treatment = models.BooleanField()
    diabetic_treatment = models.BooleanField()
    virus_treatment = models.BooleanField()
    had_blood_transfer = models.BooleanField()
    gland_treatment = models.BooleanField()
    pregnant = models.BooleanField()
    smoker = models.BooleanField()
    liver_treatment = models.BooleanField()
    notes = models.TextField(max_length=200, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def get_age_in_days(self):
        if self.age_type == 'day':
            return self.age_number
        elif self.age_type == 'month':
            return self.age_number * 30
        else:
            return self.age_number * 365
    
    def save(self, *args, **kwargs):
        if self.blood_liquidity_treatment is None:
            self.blood_liquidity_treatment = False
        
        if self.antibiotique_treatment is None:
            self.antibiotique_treatment = False
            
        if self.diabetic_treatment is None:
            self.diabetic_treatment = False
            
        if self.virus_treatment is None:
            self.virus_treatment = False
            
        if self.had_blood_transfer is None:
            self.had_blood_transfer = False
            
        if self.blood_liquidity_treatment is None:
            self.blood_liquidity_treatment = False
            
        if self.gland_treatment is None:
            self.gland_treatment = False
            
        if self.pregnant is None:
            self.pregnant = False
            
        if self.smoker is None:
            self.smoker = False
            
        if self.liver_treatment is None:
            self.liver_treatment = False
            
        super(Patient, self).save(*args, **kwargs)
    
    class Meta:
        ordering = ['-date_added']

    def __unicode__(self):
        return self.name
    
    def fasted(self):
        return self.fast_hours_count > 0

lab/patient/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Patient

class AddPatientForm(forms.ModelForm):
    def clean_pregnant(self):
        if self.cleaned_data['pregnant'] and self.cleaned_data['sex'] != 'female':
            raise forms.ValidationError("هذا الحقل للإناث فقط")
        return self.cleaned_data['pregnant']
    
    def clean_national_ID(self):
        nid = self.cleaned_data.get('national_ID')
        if nid:
            patient = Patient.objects.filter(national_ID=nid)
            if patient.count() > 0 and patient[0].national_ID != self.instance.national_ID:
                raise forms.ValidationError("مسجل من قبل")
        return nid
    class Meta:
        model = Patient

lab/patient/views.py
from django.shortcuts import render, get_object_or_404
from forms import AddPatientForm
from models import Patient
from django.http.response import HttpResponseRedirect, HttpResponseNotAllowed
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import user_passes_test, login_required

@login_required
def add(request, bid):
    if request.method not in ['GET', 'POST']:
        return HttpResponseNotAllowed(permitted_methods=['GET', 'POST'])
    
    if request.method == 'GET':
        form = AddPatientForm()
    else:
        form = AddPatientForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list_patients'))
    return render(request, 'add_patient.html', {'form':form})

@login_required
def patients(request, param=''):
    if request.method == "POST":
        param = request.POST.get("param")
    
    if not param or param == "newest":
        patients = Patient.objects.all()
    elif param == "oldest":
        patients = Patient.objects.all().order_by('date_added')
    elif param == "alphabet":
        patients = Patient.objects.all().order_by('name')
    elif param.isdigit():
        if len(param) > 10:
            patients = Patient.objects.filter(national_ID=param)
        else:
            patients =Patient.objects.filter(id=int(param))
    elif isinstance(param, basestring):
        patients = Patient.objects.filter(name__contains=param).order_by('-date_added')
    return render(request, 'patients.html', {'patients':patients})

@user_passes_test(lambda u: u.is_superuser)
def confirm_delete(request, id=0):
    patient = get_object_or_404(Patient, pk=id)
    patient.delete()
    return HttpResponseRedirect(reverse('list_patients'))

@user_passes_test(lambda u: u.is_superuser)
def delete(request, id=0):
    patient = get_object_or_404(Patient, pk=id)
    return render(request, 'delete_patient.html', {'patient':patient})

@login_required
def edit(request, id=0):
    patient = get_object_or_404(Patient, pk=id)
    if request.method == 'GET':
        form = AddPatientForm(instance=patient)
    else:
        form = AddPatientForm(request.POST, instance=patient)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list_patients'))
    return render(request, 'edit_patient.html', {'form':form})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def patient_reports(request, id=0):
    patient = get_object_or_404(Patient, pk=id)
    return render(request, 'patient_reports.html', {})

lab/patient/templates/add_patient.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
<script>
	$(document).ready(function() {

		$("#patient").addClass('selected');

	}); 
</script>
{% endblock %}

{% block body %}
<div class="panel" id="home">
	<fieldset align="center">
		<legend align="right">
			<h1>إضافة مريض</h1>
		</legend>
		<form action="{% url 'add_patient' %}" method="post">
			{% csrf_token %}
			<table align="right">
				<tr>

					<td align="right">{{form.name}}</td>
					<td align="right"><label for="id_name">:الإسم</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.name.errors}} </td>
				</tr>

				<tr>

					<td align="right">{{form.national_ID}}</td>
					<td align="right"><label for="id_national_ID">:الرقم القومى</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.national_ID.errors}} </td>
				</tr>

				<tr>

					<td align="right">{{form.sex}}</td>
					<td align="right"><label for="id_sex">:النوع</label></td>

				</tr>

				<tr>
					<td align="left"> {{form.age_type}}
					{{form.age_number}} </td>
					<td align="right"><label for="id_age_number">:العمر</label></td>

				</tr>

				<tr>
					<td align="right" style="color:red;">{{form.age_number.errors}} </td>
				</tr>

				<tr>
					<td align="right">{{form.address}}</td>
					<td align="right"><label for="id_address">:العنوان</label></td>
				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.address.errors}} </td>
				</tr>

				<tr>
					<td align="right"> {{form.telephone}}</td>
					<td align="right"><label for="id_telephone">:رقم التليفون</label></td>
				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.telephone.errors}} </td>
				</tr>
				<tr>

					<td align="right"> {{form.cell}}</td>
					<td align="right"><label for="id_cell">:الهاتف المحمول</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.cell.errors}} </td>
				</tr>

				<tr>
					<td align="right"> {{form.email}}</td>
					<td align="right"><label for="id_email">:البريد الاليكترونى</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.email.errors}} </td>
				</tr>
			</table>

			<fieldset align="right">
				<legend align="right">
					معلومات إضافية هامة
				</legend>

				<table align="right">
					<tr>
						<td> {{form.blood_liquidity_treatment}}</td>
						<td align="right"><label for="id_blood_liquidity_treatment">:يتلقى علاجا لسيولة الدم</label></td>

					</tr>
					
					<tr>
						<td> {{form.antibiotique_treatment}}</td>
						<td align="right"><label for="id_antibiotique_treatment">:يأخذ مضادات حيوية</label></td>

					</tr>
					
					<tr>
						<td> {{form.diabetic_treatment}}</td>
						<td align="right"><label for="id_diabetic_treatment">:مريض بالسكر</label></td>

					</tr>
					
					
					<tr>
						<td> {{form.virus_treatment}}</td>
						<td align="right"><label for="id_virus_treatment">:يتلقى علاجا للفيروسات</label></td>

					</tr>
					
					
					<tr>
						<td> {{form.had_blood_transfer}}</td>
						<td align="right"><label for="id_had_blood_transfer">:سبق نقل دم له</label></td>

					</tr>
					
					
					<tr>
						<td> {{form.gland_treatment}}</td>
						<td align="right"><label for="id_gland_treatment">:يأخذ علاجا للغدد</label></td>

					</tr>
					
					<tr>
						<td> {{form.pregnant}}</td>
						<td align="right"><label for="id_pregnant"> للسيدات : هل يوجد حمل؟</label></td>

					</tr>
					<tr>
					<td align="left" style="color:red;">{{form.pregnant.errors}} </td>
					</tr>
					
					
					<tr>
						<td> {{form.smoker}}</td>
						<td align="right"><label for="id_smoker">:مدخن</label></td>

					</tr>
					
					
					
					<tr>
						<td> {{form.liver_treatment}}</td>
						<td align="right"><label for="id_liver_treatment">:يتلقى علاجا للكبد</label></td>

					</tr>
					
										
				</table>
			</fieldset>
			
			<fieldset>
				<legend align="right">ملاحظات</legend>
				<table align="right">
					<tr>
						<td> {{form.notes}}</td>

					</tr>
				</table>
			</fieldset>
			
			<tr>
				<br/>
				<td align="right">
				<input type="submit" value="إضافة">
				</td>
			</tr>
		</form>
	</fieldset>
</div>
{% endblock %}

lab/patient/templates/delete_patient.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
<script>
	$(document).ready(function() {

		$("#patient").addClass('selected');

	}); 
</script>
{% endblock %}

{% block body %}

<div class="panel" id="home">
	<fieldset align="center">
		<legend align="right">
			<h1> تأكيد حذف مريض </h1>

		</legend>
		<br/>
		<table border="0" align="center" width="500">

			<tr>
				<td>{{patient.name}} </td>
				<td> اسم المريض</td>
			</tr>

			<tr>
				<td>{{patient.address}} </td>
				<td> العنوان</td>
			</tr>

			<tr>
				<td>{{patient.telephone}} </td>
				<td> التليفون</td>
				
			</tr>
			<td>{{patient.cell}} </td>
				<td> الهاتف المحمول</td>
			<tr>
				<td>{{patient.national_ID}} </td>
				<td> الرقم القومى</td>
			</tr>

			<tr>
				<td>   {% if patient.sex == "male"%} ذكر {% else %} أنثى{%endif%}</td>
				<td> النوع</td>
			</tr>

			<tr>
				<td>العمر : {{patient.age_number}} {% if patient.age_type == "year"%}سنة {% elif patient.age_type == "day"%} يوم{% elif patient.age_type == "month"%}شهر {%endif%}  </td>

			</tr>

			<tr>
				<td>البريد الاليكترونى : {{patient.email}}</td>

			</tr>

			
					<tr>
						<td> يتلقى علاجا لسيولة الدم :  {% if patient.blood_liquidity_treatment%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>
					</tr>

					<tr>
						<td> يأخذ مضادات حيوية :  {% if patient.antibiotique_treatment%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>

					</tr>

					<tr>
						<td> مريض بالسكر :  {% if patient.diabetic_treatment%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>
				
					</tr>

					<tr>
						<td> يتلقى علاجا للفيروسات :  {% if patient.virus_treatment%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>

					</tr>

					<tr>
						<td> سبق نقل دم له :  {% if patient.had_blood_transfer%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>
					</tr>

					<tr>
						<td> يأخذ علاجا للغدد :  {% if patient.gland_treatment%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>
					</tr>

					<tr>
						<td> هل يوجد حمل؟ :  {% if patient.pregnant%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>

					</tr>

					<tr>
						<td> مدخن :  {% if patient.smoker%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>

					</tr>

					<tr>
						<td> تلقى علاجا للكبد :  {% if patient.liver_treatment%}<input type="checkbox" disabled checked>{%else%}<input type="checkbox" disabled> {%endif%} </td>
					</tr>

			
					<tr>
						ملاحظات أخرى
						<td> {{patient.notes}}</td>

					</tr>

					<tr>
						<td>
						<form action="{% url 'confirm_delete_patient' patient.id %}" method="post">
							{% csrf_token %}
							<input  type="submit" value="تأكيد الحــــــــذف"/>

						</form></td>
					</tr>
				</table>

			</fieldset>

</div>
{% endblock %}

lab/patient/templates/edit_patient.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
<script>
	$(document).ready(function() {

		$("#patient").addClass('selected');

	}); 
</script>
{% endblock %}

{% block body %}
<div class="panel" id="home">
	<fieldset align="center">
		<legend align="right">
			<h1>تعديل بيانات مريض</h1>
		</legend>
		<form method="post">
			{% csrf_token %}
			<table align="right">
				<tr>

					<td align="right">{{form.name}}</td>
					<td align="right"><label for="id_name">:الإسم</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.name.errors}} </td>
				</tr>

				<tr>

					<td align="right">{{form.national_ID}}</td>
					<td align="right"><label for="id_national_ID">:الرقم القومى</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.national_ID.errors}} </td>
				</tr>

				<tr>

					<td align="right">{{form.sex}}</td>
					<td align="right"><label for="id_sex">:النوع</label></td>

				</tr>

				<tr>
					<td align="left"> {{form.age_type}}
					{{form.age_number}} </td>
					<td align="right"><label for="id_age_number">:العمر</label></td>

				</tr>

				<tr>
					<td align="right" style="color:red;">{{form.age_number.errors}} </td>
				</tr>

				<tr>
					<td align="right">{{form.address}}</td>
					<td align="right"><label for="id_address">:العنوان</label></td>
				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.address.errors}} </td>
				</tr>

				<tr>
					<td align="right"> {{form.telephone}}</td>
					<td align="right"><label for="id_telephone">:رقم التليفون</label></td>
				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.telephone.errors}} </td>
				</tr>
				<tr>

					<td align="right"> {{form.cell}}</td>
					<td align="right"><label for="id_cell">:الهاتف المحمول</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.cell.errors}} </td>
				</tr>

				<tr>
					<td align="right"> {{form.email}}</td>
					<td align="right"><label for="id_email">:البريد الاليكترونى</label></td>

				</tr>
				<tr>
					<td align="left" style="color:red;">{{form.email.errors}} </td>
				</tr>
			</table>

			<fieldset align="right">
				<legend align="right">
					معلومات إضافية هامة
				</legend>

				<table align="right">
					<tr>
						<td> {{form.blood_liquidity_treatment}}</td>
						<td align="right"><label for="id_blood_liquidity_treatment">:يتلقى علاجا لسيولة الدم</label></td>

					</tr>
					
					<tr>
						<td> {{form.antibiotique_treatment}}</td>
						<td align="right"><label for="id_antibiotique_treatment">:يأخذ مضادات حيوية</label></td>

					</tr>
					
					<tr>
						<td> {{form.diabetic_treatment}}</td>
						<td align="right"><label for="id_diabetic_treatment">:مريض بالسكر</label></td>

					</tr>
					
					
					<tr>
						<td> {{form.virus_treatment}}</td>
						<td align="right"><label for="id_virus_treatment">:يتلقى علاجا للفيروسات</label></td>

					</tr>
					
					
					<tr>
						<td> {{form.had_blood_transfer}}</td>
						<td align="right"><label for="id_had_blood_transfer">:سبق نقل دم له</label></td>

					</tr>
					
					
					<tr>
						<td> {{form.gland_treatment}}</td>
						<td align="right"><label for="id_gland_treatment">:يأخذ علاجا للغدد</label></td>

					</tr>
					
					<tr>
						<td> {{form.pregnant}}</td>
						<td align="right"><label for="id_pregnant"> للسيدات : هل يوجد حمل؟</label></td>

					</tr>
					<tr>
					<td align="left" style="color:red;">{{form.pregnant.errors}} </td>
					</tr>
					
					
					<tr>
						<td> {{form.smoker}}</td>
						<td align="right"><label for="id_smoker">:مدخن</label></td>

					</tr>
					
					
					
					<tr>
						<td> {{form.liver_treatment}}</td>
						<td align="right"><label for="id_liver_treatment">:يتلقى علاجا للكبد</label></td>

					</tr>
					
										
				</table>
			</fieldset>
			
			<fieldset>
				<legend align="right">ملاحظات</legend>
				<table align="right">
					<tr>
						<td> {{form.notes}}</td>

					</tr>
				</table>
			</fieldset>
			
			<tr>
				<br/>
				<td align="right">
				<input type="submit" value="تــعديل">
				</td>
			</tr>
		</form>
	</fieldset>
</div>
{% endblock %}

lab/patient/templates/patient_reports.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
	<script>
		$(document).ready(function(){
			
			$("#physician").addClass('selected');
    		
		});
	</script>
{% endblock %}

{% block body %}

{% endblock %}

lab/patient/templates/patients.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js%}
	<script>
		$(document).ready(function(){
			
			$("#patient").addClass('selected');
    		
		});
	</script>
{% endblock %}

{% block body %}

<div class="panel" id="home">
	
	<fieldset align="center">
	<legend align="right">
		<h1>
			بــحث عن مريض
		</h1>
	</legend>
	<form method="post" action="{% url 'list_patients'%}" align="right">
		{% csrf_token %}
		<input type="submit" value="بــحث">
		<input type="text" name="param" />
	</form>
	</fieldset>

	<fieldset align="center">
	<legend align="right">
		<h1>
			<a href="{% url 'add_patient'%}"><img src="{% static 'images/add.png'%}" title="إضافة مريض جديد"></a>
			<a href="{% url 'list_patients' 'alphabet' %}"><img src="{% static 'images/sort_ascend.png'%}" title="حسب الترتيب الأبجدى"></a>
     		<a href="{% url 'list_patients' 'oldest' %}"><img src="{% static 'images/sort.png'%}" title="الأحدث للأقدم"></a>
			<a href="{% url 'list_patients' 'newest' %}"><img src="{% static 'images/sort_reverse.png'%}" title="الأقدم للأحدث"></a>

			المرضى
		</h1>
		
	 </legend>
	<br/>
	
	{% if not patients %}
		<div align="center">عفوا .... لا توجد نتائج</div>
	{% else %}
	<table border="1" align="center" width="500">
		<tr>
		<th>أخرى</th>
		<th>الرقم القومى</th>
		<th>رقم الهاتف المحمول</th>
		<th>رقم التليفون</th>
		<th>العنوان</th>
		<th>اسم المريض</th><br />
		<th>الرقم التعريفى</th>
		
		
		</tr>
		{% for record in patients %}
		<tr>
			<td>
				{% if user.is_superuser %}
				<a href="{% url 'delete_patient' record.id %}" > 
				<img src="{% static 'images/delete.png' %}" title="حذف المريض" />
				</a>
				{% endif %}
				<a href="{% url 'patient_reports' record.id %}" > 
				<img src="{% static 'images/more_tests.png' %}" title="إضافة فحوصات"/>
				</a>
				
				<a href="{% url 'list_analysis' record.id 'all' %}" > 
				<img src="{% static 'images/more_tests.png' %}" title="عرض الفحوصات"/>
				</a>
				
				<a href="{% url 'patient_reports' record.id %}" > 
				<img src="{% static 'images/more_info.png' %}" title="الــمزيد من المعلومات" />
				</a>
				
				<a href="{% url 'patient_reports' record.id %}" > 
				<img src="{% static 'images/report.png' %}" title="عرض تقـــارير المريض" />
				</a>
				
				<a href="{% url 'add_analysis' record.id %}">إضافة فحص</a>
			</td>
			<td>{{record.national_ID}}</td>
			<td>{{record.cell}}</td>
			<td>{{record.telephone}}</td>
			<td>{{record.address}}</td>
			<td><a href="{% url 'edit_patient' id=record.id %}">{{record.name}}</a></td>
			<td>{{record.id}}</td>
		</tr>
			{% endfor %}
	</table>
{%endif%}
</fieldset>				

</div>
{% endblock %}